### ISSUE TITLE
In karma conf, is the 'plugins' entry really needed?

### ISSUE THREAD

**Issue by 03xb7** [alonronin/angular-webpack-boilerplate#1]
First of all, thanks for your example application.

I have barely the same code as you (expect I use Jasmine). In my conf file I don't need the `plugins` entry for webpack to work. Could you give more details about why you added it?

Thanks

**Comment by alonronin** [comment]
It is just a leftover, no need for annotation there, although if you use something like providePlugin it is necessary as it loads the module and inject it's var.

**Comment by 03xb7** [comment]
Ok cool
