### ISSUE TITLE
question how to exclude webpack.karma.context.js from coverage report

### ISSUE THREAD

**Issue by andypeng2015** [alonronin/angular-webpack-boilerplate#2]
hi Alon @alonronin  I found my webpack.karma.context.js is included in coverage report,how can I exclude it? thanks

**Comment by alonronin** [comment]
it is not really related to this repo, however a quick search in google result this:
http://stackoverflow.com/questions/29135575/how-do-i-exclude-files-from-karma-code-coverage-report
